int {ParameterName}_GaussianCount;
int {ParameterName}_SHCoefficientsCount;

Buffer<float4> {ParameterName}_GaussianPositionBuffer;
Buffer<float4> {ParameterName}_GaussianSHCoefficientsBuffer;

void {GetGaussianDataName}_{ParameterName}(out float4 OutPosition, out int OutIndex)
{
	int GaussianCount = {ParameterName}_GaussianCount;
	int Index = ExecIndex() % GaussianCount;
	
	OutPosition = {ParameterName}_GaussianPositionBuffer[Index];
	OutIndex = Index;
}